import { ResearchRun } from './types';

const DEMO_ANSWER =
  'Moderate daily creatine intake is associated with improved memory retention in select aging populations. Creatine supplementation produces measurable cognitive performance gains within one week of administration. Creatine monohydrate supplementation provides universal cognitive enhancement to every older adult demographic.';
const quote = (value: string) => ({
  quote: value,
  startIndex: DEMO_ANSWER.indexOf(value),
  endIndex: DEMO_ANSWER.indexOf(value) + value.length,
  matchStatus: 'exact' as const,
});

export const MOCK_RESEARCH_RUN: ResearchRun = {
  id: 'run-mock-001',
  query: DEMO_ANSWER,
  summary:
    'The audit found limited support for a population-specific memory association, while the one-week and universal-enhancement claims are contradicted or unsupported by the retained evidence. The evidence trail is useful for review, but it does not establish a universal effect.',
  createdAt: new Date().toISOString(),
  mode: 'demo',
  workflowMode: 'audit',
  providerMetadata: { fallbackUsed: false },
  summaryMetadata: {
    generatedAt: new Date().toISOString(),
    stale: false,
    staleReason: null,
  },
  agentTrace: [
    { id: 'stage-1', role: 'researcher', label: 'Initial Tavily research search', status: 'skipped', durationMs: 0, inputCount: 0, outputCount: 0, note: 'Audit mode uses the pasted answer as its source context.' },
    { id: 'stage-2', role: 'claim-decomposer', label: 'Gemini atomic claim extraction', status: 'completed', durationMs: 810, inputCount: 1, outputCount: 3, note: 'Claims were extracted from the pasted answer only.' },
    { id: 'stage-3', role: 'challenger', label: 'Support and challenge evidence retrieval', status: 'completed', durationMs: 1240, inputCount: 6, outputCount: 8, note: 'Support and challenge searches ran in parallel.' },
    { id: 'stage-4', role: 'source-reader', label: 'Tavily focused source extraction', status: 'completed', durationMs: 980, inputCount: 8, outputCount: 8, note: 'Focused source passages were retained with snippet fallback where needed.' },
    { id: 'stage-5', role: 'verifier', label: 'Gemini evidence verification', status: 'completed', durationMs: 920, inputCount: 8, outputCount: 3, note: 'All extracted claims were verified against retained evidence.' },
    { id: 'stage-6', role: 'synthesizer', label: 'Final synthesis', status: 'completed', durationMs: 610, inputCount: 3, outputCount: 1, note: 'Summary compiled from verified claim decisions only.' },
  ],
  manifest: {
    manifestVersion: '1.0',
    pipelineVersion: '2.0',
    workflowMode: 'audit',
    generatedAt: new Date().toISOString(),
    model: 'gemini-3.6-flash',
    buildRulesVersion: '1.0',
    sourceIndependenceVersion: '1.0',
    claimCount: 3,
    sourcesScanned: 8,
    retainedEvidenceCount: 5,
    focusedExtractCount: 4,
    snippetFallbackCount: 1,
    distinctDomains: 5,
    fallbackUsed: false,
    stageDurationsMs: {
      researcher: 0,
      'claim-decomposer': 810,
      challenger: 1240,
      'source-reader': 980,
      verifier: 920,
      synthesizer: 610,
    },
    searchQueries: [
      { claimId: 'claim-1', supportQuery: 'creatine memory aging systematic review', challengeQuery: 'creatine memory aging null trial' },
      { claimId: 'claim-2', supportQuery: 'creatine one week cognitive performance trial', challengeQuery: 'creatine acute seven day cognitive trial' },
      { claimId: 'claim-3', supportQuery: 'creatine universal cognitive enhancement older adults', challengeQuery: 'creatine cognitive response heterogeneity older adults' },
    ],
  },
  buildResult: {
    status: 'fail',
    headline: 'Verification build failed',
    explanation: 'One or more extracted claims failed verification or were directly contradicted by evidence.',
    passedClaims: 1,
    warningClaims: 0,
    failedClaims: 2,
  },
  metrics: {
    durationMs: 4560,
    sourcesScanned: 8,
    extractedSources: 4,
    snippetFallbackSources: 1,
    distinctDomains: 5,
    supportedClaims: 1,
    challengedClaims: 2,
    insufficientClaims: 0,
  },
  claims: [
    {
      id: 'claim-1',
      text: 'Moderate daily creatine intake is associated with improved memory retention in select aging populations.',
      sourceQuote: 'Moderate daily creatine intake is associated with improved memory retention in select aging populations.',
      verdict: 'supported',
      confidence: 0.82,
      explanation: 'The retained review and cohort passages support a population-specific association, but they do not establish a universal treatment effect.',
      claimBuildStatus: 'pass',
      confidenceFactors: { evidenceCount: 2, distinctDomains: 2, hasContradiction: false, appliedCap: null },
      sourceIndependence: { sourceCount: 2, independentOrigins: 2, duplicateGroups: 0, syndicatedSourceCount: 0 },
      missingEvidence: 'A larger preregistered trial across older adults with different baseline diets.',
      nextBestQuery: 'creatine memory retention older adults preregistered randomized trial',
      searchQueries: { support: 'creatine memory aging systematic review', challenge: 'creatine memory aging null trial' },
      auditAnchor: quote('Moderate daily creatine intake is associated with improved memory retention in select aging populations.'),
      evidence: [
        { id: 'ev-1', title: 'Creatine and Cognitive Function in Aging', url: 'https://example.org/creatine-aging-review', domain: 'example.org', excerpt: 'A review reports modest memory associations in selected aging populations.', stance: 'support', relevanceScore: 0.92, evidenceBasis: 'focused-source-extract', originGroupId: 'origin-1' },
        { id: 'ev-2', title: 'Dietary Creatine and Memory Outcomes', url: 'https://example.net/dietary-creatine-memory', domain: 'example.net', excerpt: 'A cohort analysis reports an association between intake and memory retention.', stance: 'support', relevanceScore: 0.84, evidenceBasis: 'focused-source-extract', originGroupId: 'origin-2' },
      ],
    },
    {
      id: 'claim-2',
      text: 'Creatine supplementation produces measurable cognitive performance gains within one week of administration.',
      sourceQuote: 'Creatine supplementation produces measurable cognitive performance gains within one week of administration.',
      verdict: 'contradicted',
      confidence: 0.9,
      explanation: 'The retained trial passage reports no measurable acute cognitive improvement after a one-week intervention.',
      claimBuildStatus: 'fail',
      confidenceFactors: { evidenceCount: 2, distinctDomains: 2, hasContradiction: true, appliedCap: null },
      sourceIndependence: { sourceCount: 2, independentOrigins: 2, duplicateGroups: 0, syndicatedSourceCount: 1 },
      missingEvidence: 'A controlled trial that measures cognitive outcomes after exactly seven days.',
      nextBestQuery: 'acute seven day creatine cognitive performance randomized trial',
      searchQueries: { support: 'creatine one week cognitive performance trial', challenge: 'creatine acute seven day cognitive trial' },
      auditAnchor: quote('Creatine supplementation produces measurable cognitive performance gains within one week of administration.'),
      evidence: [
        { id: 'ev-3', title: 'Short-Term Creatine Loading and Cognitive Performance', url: 'https://example.org/creatine-seven-day-trial', domain: 'example.org', excerpt: 'The seven-day intervention did not produce a measurable cognitive performance gain.', stance: 'contradict', relevanceScore: 0.95, evidenceBasis: 'focused-source-extract', originGroupId: 'origin-3' },
        { id: 'ev-4', title: 'Syndicated: Short-Term Creatine Loading and Cognitive Performance', url: 'https://example.com/creatine-seven-day-trial', domain: 'example.com', excerpt: 'The same seven-day result was republished with matching title and passage.', stance: 'contradict', relevanceScore: 0.88, evidenceBasis: 'focused-source-extract', originGroupId: 'origin-3' },
      ],
    },
    {
      id: 'claim-3',
      text: 'Creatine monohydrate supplementation provides universal cognitive enhancement to every older adult demographic.',
      sourceQuote: 'Creatine monohydrate supplementation provides universal cognitive enhancement to every older adult demographic.',
      verdict: 'insufficient',
      confidence: 0.42,
      explanation: 'The retained evidence shows heterogeneous responses and does not support a universal benefit across every demographic.',
      claimBuildStatus: 'fail',
      confidenceFactors: { evidenceCount: 1, distinctDomains: 1, hasContradiction: false, appliedCap: 'Capped at 45% (Insufficient evidence limits score)' },
      sourceIndependence: { sourceCount: 1, independentOrigins: 1, duplicateGroups: 0, syndicatedSourceCount: 0 },
      missingEvidence: 'Stratified trials comparing baseline diet, age, sex, and cognitive status.',
      nextBestQuery: 'creatine cognitive response heterogeneity older adults stratified trial',
      searchQueries: { support: 'creatine universal cognitive enhancement older adults', challenge: 'creatine cognitive response heterogeneity older adults' },
      auditAnchor: quote('Creatine monohydrate supplementation provides universal cognitive enhancement to every older adult demographic.'),
      evidence: [
        { id: 'ev-5', title: 'Heterogeneous Cognitive Responses to Creatine', url: 'https://example.edu/creatine-response-heterogeneity', domain: 'example.edu', excerpt: 'Response varied by baseline dietary intake and cognitive status.', stance: 'neutral', relevanceScore: 0.81, evidenceBasis: 'search-snippet', originGroupId: 'origin-4' },
      ],
    },
  ],
};
